export const serverMessageKeys = {
  conectionSize: "conectionSize",
  heartbeat: "heartbeat",
  inference: "inference",
  join: "join",
  challenge: "challenge",
  joinAck: "joinAck",
  leave: "leave",
  newConversation: "newConversation",
  providerDetails: "providerDetails",
  reportCompletion: "reportCompletion",
  requestProvider: "requestProvider",
  sessionValid: "sessionValid",
  verifySession: "verifySession",
} as const;
